name: GitHub Pages

on:
  push:
    branches:
      - main # Or your primary branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add any other steps to install dependencies, e.g., for Node.js
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # Ensure this outputs files to the /dist directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
